FROM golang:alpine

WORKDIR /app

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Command to run air
CMD ["air", "-c", ".air.toml"]
